// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   ../@utkusarioglu/m_namespace

declare module '@utkusarioglu/book' {
    import { M_Namespace, t_namespace } from "@utkusarioglu/m_namespace";
    import { t_resolutionRules, t_libraryContent, i_libraryBook } from "@utkusarioglu/book/t_book";
    export interface Book extends M_Namespace {
    }
    const Book_base: any;
    export class Book extends Book_base {
        readonly RESOLUTION_RULES: t_resolutionRules;
        constructor(namespace: t_namespace);
        add_Chapter(item_name: string, item_data: any, per_item_call?: (item: any) => any): this;
        get_Chapter(item_name: string): any;
        has_Chapter(item_name: string): boolean;
        get_AllChapters(): i_libraryBook;
        get_AllChapterNames(): string[];
        add_BookContent(library_content: any, per_item_call?: (item: any) => any): this;
        add_Books(library_set: t_libraryContent, per_item_call?: (item: any) => any): this;
    }
    export {};
}

declare module '@utkusarioglu/book/t_book' {
    export type t_libraryContent = i_genericMap<any> | Array<any> | string | number;
    export type i_libraryBook = i_genericMap<any>;
    export type t_resolutionRules = i_genericMap<Array<string | undefined>>;
    interface i_genericMap<T> {
        [key: string]: T;
    }
    export {};
}

